### ISSUE TITLE
[🐛 BUG] - can't build on windows

### ISSUE THREAD

**Issue by stevenhurwitt** [alexkim205/G-Desktop-Suite#95]
**Describe the bug**
the repo will not build out of the box on windows

**To Reproduce**
1. be on windows
2. git clone, yarn install, ctrl+shift+b
3. get this error

```
• writing effective config  file=dist\builder-effective-config.yaml
  ⨯ Build for macOS is supported only on macOS, please see https://electron.build/multi-platform-build
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gdesktopsuite@0.3.2 build: `electron-builder -mwl -p never`
npm ERR! Exit status 1
```

**Expected behavior**
compiled & built desktop app

**G Desktop Suite:**
 - latest

**Platform:**
 - OS: Windows
 - Version: most recent insiders build (20H2?)

**Comment by stevenhurwitt** [comment]
turns out i can't build it on macosx either, with a different error:

```
⨯ /Volumes/samsung/G-Desktop-Suite/node_modules/app-builder-bin/mac/app-builder exited with code 

ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  stackTrace=
Error: /Volumes/samsung/G-Desktop-Suite/node_modules/app-builder-bin/mac/app-builder exited with code 

ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
at ChildProcess.<anonymous> (/Volumes/samsung/G-Desktop-Suite/node_modules/builder-util/src/util.ts:243:14)
at Object.onceWrapper (events.js:422:26)
at ChildProcess.emit (events.js:315:20)
at maybeClose (internal/child_process.js:1021:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gdesktopsuite@0.3.2 build: `electron-builder -mwl -p never`
npm ERR! Exit status 1
```
